buildscript {
    repositories {
        maven { url = "https://jitpack.io" }
        mavenCentral()
    }
    dependencies {
        classpath "com.github.Fallen-Breath:preprocess:610499e906"
    }
}

plugins {
    id("fabric-loom").version("1.3-SNAPSHOT").apply(false)
    id("io.github.juuxel.loom-vineflower").version("1.11.0").apply(false)
    id("net.kyori.blossom").version("1.3.1").apply(false)
    id("org.ajoberstar.grgit").version("5.2.0")
    id("maven-publish")
}

apply plugin: "com.replaymod.preprocess"

preprocess {
    createNode("1.20.1", 12001, "mojang")
}

allprojects {
    apply plugin: "com.replaymod.preprocess"
}

ext {
    def environmentMap = System.getenv()
    getVersionGit = { List paths ->
        if (grgit == null) return "nogit"
        def latest = paths.isEmpty() ? grgit.log(maxCommits: 1) : grgit.log(paths: paths, maxCommits: 1)
        return latest.isEmpty() ? "uncommited" : "${latest.get(0).id.substring(0, 7)}"
    }
    getVersionPatch = { List paths ->
        if (grgit == null) return 0
        return paths.isEmpty() ? grgit.log().size() : grgit.log(paths: paths).size()
    }
    getVersionType = { environmentMap.BUILD_TYPE == "RELEASE" ? "stable" : "dev" }
    getMavenArtifactVersion = { ext.getVersionType() == "stable" ? "${project.mod_version}.${ext.getVersionPatch([])}" : project.version }
}

version("${project.mod_version}.${project.getVersionPatch([])}+${project.getVersionGit([])}-${project.getVersionType()}")
