buildscript {
    repositories {
        maven { url = "https://jitpack.io" }
        mavenCentral()
    }
    dependencies {
        classpath "com.github.Fallen-Breath:preprocess:c5abb4fb12"
    }
}

plugins {
    id 'maven-publish'
    id 'org.ajoberstar.grgit' version '5.2.0'
    // 升级 Loom 版本到 1.7-SNAPSHOT (适配 1.20.1)
    id 'net.fabricmc.loom' version '1.7-SNAPSHOT' apply false
    id 'io.github.juuxel.loom-vineflower' version '1.11.0' apply false
    id 'net.kyori.blossom' version '1.3.1' apply false
}

apply plugin: "com.replaymod.preprocess"

preprocess {
    def mc1201 = createNode('1.20.1', 1_20_01, '')

    for (final def node in getNodes()) {
        def p = findProject(node.project)
        if (p != null) {
            p.ext.mcVersion = node.mcVersion
        }
    }
}

version = "${project.mod_version}+build.${System.getenv("GITHUB_RUN_NUMBER") ?: "dev"}"
