apply plugin: "fabric-loom"
apply plugin: "io.github.juuxel.loom-vineflower"
apply plugin: "maven-publish"
apply plugin: "net.kyori.blossom"
apply plugin: "com.replaymod.preprocess"

int mcVersion = 0
preprocess {
    def val = vars.get()["MC"]
    if (val != null) {
        mcVersion = val instanceof Integer ? val : Integer.parseInt(val.toString())
    }
    tabIndentation.set(false)
}

repositories {
    mavenLocal()
    maven { 
        name = "HendrixShen"
        url = "https://maven.hendrixshen.top/" 
    }
    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content { includeGroup("curse.maven") }
    }
    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
        content { includeGroup("maven.modrinth") }
    }
    maven {
        name = "Jitpack Maven"
        url = "https://jitpack.io"
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modCompileOnly "org.projectlombok:lombok:${project.lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${project.lombok_version}"

    modImplementation("top.hendrixshen.magiclib:magiclib-${project.minecraft_version.replace(".", "_")}:${project.magiclib_version}") {
        exclude group: "carpet", module: "fabric-carpet"
    }

    def deps = [
        ["curse.maven:minihud-244260", "minihud"],
        ["curse.maven:litematica-308892", "litematica"],
        ["maven.modrinth:client-commands", "clientcommands"]
    ]

    deps.forEach { item ->
        String notation = item[0]
        String prefix = item[1]
        if (project.hasProperty("${prefix}_version")) {
            modApi("${notation}:${project.property("${prefix}_version")}") {
                transitive(prefix == "clientcommands")
            }
        }
    }

    runtimeOnly project(path: ":fabricWrapper")
}

group = project.mod_maven_group
version = project.parent.version

base {
    archivesName = "${project.mod_archives_base_name}-${project.minecraft_version}"
}

loom {
    interfaceInjection {
        enableDependencyInterfaceInjection.set(true)
    }

    runConfigs.configureEach {
        property "mixin.debug.export", "true"
    }

    runs {
        client {
            runDir "run/client"
        }
        server {
            runDir "run/server"
        }
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(17)
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand([
                "magiclib_dependency" : project.magiclib_dependency,
                "minecraft_dependency": project.minecraft_dependency,
                "minecraft_version"   : project.minecraft_version,
                "mod_description"     : project.mod_description,
                "mod_homepage"        : project.mod_homepage,
                "mod_id"              : project.mod_id,
                "mod_license"         : project.mod_license,
                "mod_name"            : project.mod_name,
                "mod_sources"         : project.mod_sources,
                "mod_version"         : project.version
        ])
    }

    from("${rootDir}/icon.png") {
        into("assets/${project.mod_id}")
    }
}

blossom {
    replaceToken("@MOD_IDENTIFIER@", project.mod_id)
    replaceToken("@MOD_NAME@", project.mod_name)
    replaceToken("@MINECRAFT_VERSION_IDENTIFY@", project.minecraft_version.replace(".", "_"))
}

jar {
    from("${rootDir}/LICENSE")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${project.mod_id}-${project.minecraft_version.replace(".", "_")}"
            from components.java
        }
    }
    repositories {
        maven {
            url = "$rootDir/publish"
        }
    }
}
