# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod
mod_id=bladeren
mod_name=Bladeren
mod_version=1.1
maven_group=top.leavesmc
mod_archives_base_name=Bladeren
minecraft_version=1.20.1
minecraft_dependency=>=1.20.1

# Deps
magiclib_dependency=0.7.345
magiclib_version=0.7.345
lombok_version=1.18.28

# Dependencies Versions
minihud_version=0.17.0
litematica_version=0.15.3
clientcommands_version=2.6.2
