pluginManagement {
    repositories {
        mavenLocal()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://jitpack.io" } // 允许从 jitpack 加载插件
        maven { url = "https://maven.hendrixshen.top/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "Bladeren"

def versions = ["1.20.1"]
for (String version : versions) {
    include(":$version")
    project(":$version").projectDir = file("versions/$version")
    project(":$version").buildFileName = "../../common.gradle"
}
include(":fabricWrapper")
